### ISSUE TITLE
[BUG] Command not working when sending "true" to PnP Bridge

### ISSUE THREAD

**Issue by ChenhangLin** [Azure/iot-plug-and-play-bridge#58] opened 2021-04-12 13:22 UTC
**Describe the bug**

Customer was testing IoT PnP bridge and trying to send commands with string containing boolean information to Modsim and real Modbus devices via PnP bridge, but only false/0 works, but true/1 does not work.

Customer tested command on real Modbus device  and the results are familiar with on Modsim.

To sum up, pnpbridge.exe fails to set Modbus coil type to true, but it’s okay to set to false.

**To Reproduce**

Please refer to customer's testing process.

**On Real Modbus device:

Set 1 from IoT Central -> Failed**
 
![image](https://user-images.githubusercontent.com/61225358/114400381-7ac47700-9bd4-11eb-99d7-1f81c69e53ee.png)

Error message:
 
![image](https://user-images.githubusercontent.com/61225358/114400433-87e16600-9bd4-11eb-96b8-80a52599071a.png)

Info: Received PnP command for component=ModbusComponent, command=fan
Error: Time:Wed Apr 7 00:47:34 2021 File:F:\b1\pnpbridge\src\adapters\src\modbus_pnp\ModbusConnection\ModbusConnection.c Func:ValidateModbusResponse Line:42 Modbus exception code: 0x3
Error: Time:Wed Apr 7 00:47:34 2021 File:F:\b1\pnpbridge\src\adapters\src\modbus_pnp\ModbusConnection\ModbusConnection.c Func:ModbusPnp_WriteToCapability Line:598 Invalid response for command "fan".

**Set True from IoT Central -> Failed**
 
![image](https://user-images.githubusercontent.com/61225358/114400510-9f205380-9bd4-11eb-8144-24e87f584eb9.png)

No error message also no response.

**Set 0 from IoT Central -> Successful**

Before:
 
![image](https://user-images.githubusercontent.com/61225358/114400630-bb23f500-9bd4-11eb-8da4-0ead3a009798.png)

After:
 
![image](https://user-images.githubusercontent.com/61225358/114400666-c5de8a00-9bd4-11eb-8775-8e537bfb82a6.png)

Command was set immediately.

**Set false from IoT Central -> Successful**

Before:
![image](https://user-images.githubusercontent.com/61225358/114400709-d42ca600-9bd4-11eb-93b2-6eb0e80938e5.png)

After:
 
![image](https://user-images.githubusercontent.com/61225358/114400735-da228700-9bd4-11eb-8ccd-71c007581b03.png)

Command was set immediately.

**On Modsim:

Set 1 from IoT Central -> Failed**
 
![image](https://user-images.githubusercontent.com/61225358/114400793-e7d80c80-9bd4-11eb-9b4c-430b2dd9f136.png)

No error message also no response.

**Set true from IoT Central -> Failed**
 
![image](https://user-images.githubusercontent.com/61225358/114400824-ee668400-9bd4-11eb-8737-7196a7d5752f.png)

No error message also no response.

**Set 0 from IoT Central -> Successful**

Before:
 
![image](https://user-images.githubusercontent.com/61225358/114400858-f9211900-9bd4-11eb-9bce-b6cdc263e14c.png)

After:
 
![image](https://user-images.githubusercontent.com/61225358/114400876-ff16fa00-9bd4-11eb-925b-afc5dba553a7.png)

Command was set immediately.

**Set false from IoT Central -> Successful**

Before:
 
![image](https://user-images.githubusercontent.com/61225358/114400936-0ccc7f80-9bd5-11eb-8743-dadaa85a6765.png)

After:
 
![image](https://user-images.githubusercontent.com/61225358/114400977-148c2400-9bd5-11eb-8d71-7a62ca2e5a66.png)

Command was set immediately.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, or Windows (Version 2004)]
 - Copy of the config.json file
 - Copy of PnP interface json

**Additional context**

**Comment by ChenhangLin** [comment] 2021-04-12 13:23
Moved the thread here due to IoT Central PG suggestions.

**Comment by usivagna** [comment] 2021-04-12 22:13
Thanks for filing this issue @ChenhangLin, we'll review and investigate. @dipannita08  can you have a look at this bug?

**Comment by dipannita08** [comment] 2021-04-15 21:26
I have not yet been able to reproduce this issue using Azure IoT explorer or Azure  IoT hub. It would be helpful to either repro the issue or look at logs to further investigate.

Please provide the following information:
1. PnpBridge logs
2. IoT Hub logs (set pnp_bridge_debug_trace to true)
3. Command response status
4. Does this issue reproduce on Azure IoT Explorer or Azure IoT Hub?

I can provide more information on what is happening after looking at the logs.

**Comment by ChenhangLin** [comment] 2021-04-16 00:26
Hi Dipannita,

Customer hasn’t tested on IoT Hub and Explorer. They were only testing on IoT Central and ModSim. PnP bridge logs are also included in the GitHub issue.

Thanks!

Best Regards,
Clive Lin
________________________________
发件人: Dipannita Shaw ***@***.***>
发送时间: Friday, April 16, 2021 5:26:48 AM
收件人: Azure/iot-plug-and-play-bridge ***@***.***>
抄送: Clive Lin ***@***.***>; Mention ***@***.***>
主题: Re: [Azure/iot-plug-and-play-bridge] [BUG] Command not working when sending "true" to PnP Bridge (#58)


I have not yet been able to reproduce this issue using Azure IoT explorer or Azure IoT hub. It would be helpful to either repro the issue or look at logs to further investigate.

Please provide the following information:

  1.  PnpBridge logs
  2.  IoT Hub logs (set pnp_bridge_debug_trace to true)
  3.  Command response status
  4.  Does this issue reproduce on Azure IoT Explorer or Azure IoT Hub?

I can provide more information on what is happening after looking at the logs.

―

**Comment by ChenhangLin** [comment] 2021-04-16 00:27
Will also suggest customer to set debug trace to true to see if there’s more information

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Clive Lin ***@***.***>
发送时间: Friday, April 16, 2021 8:26:26 AM
收件人: Azure/iot-plug-and-play-bridge ***@***.***>; Azure/iot-plug-and-play-bridge ***@***.***>
抄送: Mention ***@***.***>
主题: Re: [Azure/iot-plug-and-play-bridge] [BUG] Command not working when sending "true" to PnP Bridge (#58)

Hi Dipannita,

Customer hasn’t tested on IoT Hub and Explorer. They were only testing on IoT Central and ModSim. PnP bridge logs are also included in the GitHub issue.

Thanks!

Best Regards,
Clive Lin
________________________________
发件人: Dipannita Shaw ***@***.***>
发送时间: Friday, April 16, 2021 5:26:48 AM
收件人: Azure/iot-plug-and-play-bridge ***@***.***>
抄送: Clive Lin ***@***.***>; Mention ***@***.***>
主题: Re: [Azure/iot-plug-and-play-bridge] [BUG] Command not working when sending "true" to PnP Bridge (#58)


I have not yet been able to reproduce this issue using Azure IoT explorer or Azure IoT hub. It would be helpful to either repro the issue or look at logs to further investigate.

Please provide the following information:

  1.  PnpBridge logs
  2.  IoT Hub logs (set pnp_bridge_debug_trace to true)
  3.  Command response status
  4.  Does this issue reproduce on Azure IoT Explorer or Azure IoT Hub?

I can provide more information on what is happening after looking at the logs.

―

**Comment by ChenhangLin** [comment] 2021-04-16 09:18
Hi Dipannita,

Customer is using PnP Bridge exe to interact with IoT Central and ModSim. Commands will be sent from IoT Central with contents of “true”/”false”/”1”/”0”, and of string type.

We suggested customer to enable debug trace and following are the results:

Command “false” -> successful
***@***.***D732E4.81419490]

Command “0” -> successful
***@***.***D732E4.81419490]

Command “true” -> No response
***@***.***D732E4.81419490]

Command “1” -> No response
***@***.***D732E4.81419490]


Kindly let us know if more information is needed.

Thanks.

Best Regards,
Clive Lin

Clive Lin | Support Engineer | Azure IoT/AI Support Team | Asia Pacific & Greater China Region
Phone: +86 (21) 52638659
Email:  ***@***.******@***.***>
Working Hours: Mon-Fri 9:00-17:30 (GMT+8)
***@***.***D732E4.81419490]
If you have any feedback about my work, please let either me or my manager Lynn Zhang know at ***@***.******@***.***>

**Comment by usivagna** [comment] 2021-04-16 20:42
Thanks for the additional details, we will investigate further and provide an update in the next week or so.

**Comment by dipannita08** [comment] 2021-04-22 02:01
I found a bug in PnpBridge. The one line fix is in this [pull request](https://github.com/Azure/iot-plug-and-play-bridge/pull/60), however, this fix will not fix the issue you are seeing for following reasons:

1. From the few lines of logs I'm seeing in the images you uploaded here is what is happening 

- The command update callback method calls ModbusPnp_WriteToCapability before writing the response
- ModbusPnp_WriteToCapability sets and send the "write request" to the device successfully
- ModbusPnp_WriteToCapability receives the "response to the request" and tries to validate it but fails.
- The reason validation fails for the response is because response received at header size does not match the request's, rather (response[HEADER_SIZE] == request[HEADER_SIZE] + **0x80**) 

2. I was able to validate command request and response with a real modbus sensor from Azure IoT central (config and dtml can be found in the PR with the bug fix above)

This does not look like a PnP Bridge issue, rather an issue with a possible mismatch in the config and the device spec. Please also ensure that the "modbus component" is a child of the "pnpbridge root device" and both are modeled correctly with valid DTMIs when interacting with them via Azure IoT Central. 

If you would like me to further help with this investigation please attach the following:
1. The PnP Bridge logs with debug trace disabled ("pnp_bridge_debug_trace": false). (Please attach a text file with all the logs preceding the error messages and not images of isolated error messages)
2. The PnP Bridge logs with debug trace enabled ("pnp_bridge_debug_trace": true)  (Please attach a text file with all the logs preceding the error messages and not images of isolated error messages)
3. The json config file you are using for the device.
4. The device capability model, or the DTMI json.

**Comment by ChenhangLin** [comment] 2021-04-23 08:24
Hi @dipannita08 , thanks a lot for looking into this!

Attaching required information:

[LogsAndModel.zip](https://github.com/Azure/iot-plug-and-play-bridge/files/6363831/LogsAndModel.zip)

Customer Notes:

There are two txt files are logged from pnpbridge.exe, collecting telemetry for seconds and issuing command from IoT Central (set false then set true). 
Environmental Sensor.json is capacity model but I don’t import it as template on IoT Central now, I add component manually instead.
So I export the template from IoT Central, WISE-4012.json

**Comment by dipannita08** [comment] 2021-04-26 21:54
1. Your pnpbridge config should point to the "root interface model id" not the "component model id". It should be something like the one described here: [pnpbridge/docs/schemas/RootPnpBridgeInterfaceModel.json](https://github.com/Azure/iot-plug-and-play-bridge/blob/c0be198cb2cde7aaaf450b03113d861bc6596bad/pnpbridge/docs/schemas/RootPnpBridgeInterfaceModel.json). My assumption is that you created components from the IoT Central user interface and imported the WISE-4012.json DTMI for this component. Even if you do it this way, your root level interface model should list this component (DTMI) as one of its own components (as described in the example above)
2. Your modbus component described by *dtmi:evelynpnpbridge:WISE4012z9;1* does not define a command response - it only defines a request - for example, look at the dtmi models in the docs folder. [Here ](https://github.com/Azure/iot-plug-and-play-bridge/blob/c0be198cb2cde7aaaf450b03113d861bc6596bad/pnpbridge/docs/schemas/CO2Sensor.json)is one for a modbus sensor.
3. Neither of the logs in the attached compressed folder you shared show the problem reproduced. Please upload full logs (with and without hub tracing enabled) including the bug repro condition.

**Comment by ChenhangLin** [comment] 2021-04-29 02:47
Hi Dipannita,

Thanks for the information. Customer would like to record a reproduce video and include related logs later, but would like to clarify something first:


  1.  Your pnpbridge config should point to the "root interface model id" not the "component model id". It should be something like the one described here: pnpbridge/docs/schemas/RootPnpBridgeInterfaceModel.json<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fiot-plug-and-play-bridge%2Fblob%2Fc0be198cb2cde7aaaf450b03113d861bc6596bad%2Fpnpbridge%2Fdocs%2Fschemas%2FRootPnpBridgeInterfaceModel.json&data=04%7C01%7CEvelyn.Tang%40advantech.com.tw%7C7bc88c641e8f44442e1c08d90a28a410%7Ca77d40d9dcba4ddab5715f18e6da853f%7C1%7C0%7C637551991997611191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=64tjxRoAHmFQdaItmfzvKbUfInDJBu831FciDhQbHCk%3D&reserved=0>. My assumption is that you created components from the IoT Central user interface and imported the WISE-4012.json DTMI for this component. Even if you do it this way, your root level interface model should list this component (DTMI) as one of its own components (as described in the example above)
I didn't import any interface model on IoT Central. I add all the component manually.
Device templates: Create IoT device -> Create Custom model -> Add component -> Create Custom component interface -> Add capabilities manually
WISE-4012 is exported directly from above steps so I don't know how to create root level interface. If it matters, please advise me how to do.

  1.  Your modbus component described by dtmi:evelynpnpbridge:WISE4012z9;1 does not define a command response - it only defines a request - for example, look at the dtmi models in the docs folder. Here <https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fiot-plug-and-play-bridge%2Fblob%2Fc0be198cb2cde7aaaf450b03113d861bc6596bad%2Fpnpbridge%2Fdocs%2Fschemas%2FCO2Sensor.json&data=04%7C01%7CEvelyn.Tang%40advantech.com.tw%7C7bc88c641e8f44442e1c08d90a28a410%7Ca77d40d9dcba4ddab5715f18e6da853f%7C1%7C0%7C637551991997621182%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=eZeKxzNOwRjM2IyKlPk3h4I6W7z0eftJp2L0GM0cudk%3D&reserved=0> is one for a modbus sensor.
After adding response (type: string) manually, I got the same test results.
***@***.***D73CE4.FD6D7CA0]

Could you help clarify might these be the issue customer saw the issue, or customer still has to provide more detailed logs for further investigation.

Thanks!

Best Regards,
Clive Lin

Clive Lin | Support Engineer | Azure IoT/AI Support Team | Asia Pacific & Greater China Region
Phone: +86 (21) 52638659
Email:  ***@***.******@***.***>
Working Hours: Mon-Fri 9:00-17:30 (GMT+8)
***@***.***D73CE4.FD6D7CA0]
If you have any feedback about my work, please let either me or my manager Lynn Zhang know at ***@***.******@***.***>

**Comment by ChenhangLin** [comment] 2021-04-30 13:50
Hi Dipannita,

Thanks for the information. Customer would like to record a reproduce video and include related logs later, but would like to clarify something first:

1.	Your pnpbridge config should point to the "root interface model id" not the "component model id". It should be something like the one described here: pnpbridge/docs/schemas/RootPnpBridgeInterfaceModel.json. My assumption is that you created components from the IoT Central user interface and imported the WISE-4012.json DTMI for this component. Even if you do it this way, your root level interface model should list this component (DTMI) as one of its own components (as described in the example above) 

**I didn’t import any interface model on IoT Central. I add all the component manually.
Device templates: Create IoT device -> Create Custom model -> Add component -> Create Custom component interface -> Add capabilities manually
WISE-4012 is exported directly from above steps so I don’t know how to create root level interface. If it matters, please advise me how to do.**

2.	Your modbus component described by dtmi:evelynpnpbridge:WISE4012z9;1 does not define a command response - it only defines a request - for example, look at the dtmi models in the docs folder. Here is one for a modbus sensor.
After adding response (type: string) manually, I got the same test results. 
 
![image](https://user-images.githubusercontent.com/61225358/116704245-c6ad5380-a9fd-11eb-86f3-e2e6b2e02e67.png)


**Could you help clarify will above two points cause the original issue, or customer still has to provide more detailed logs/operational videos for further investigation?**

Thanks!

**Comment by ChenhangLin** [comment] 2021-06-07 16:53
Hi @dipannita08 , thanks for the information! Customer came back to try this, and copy the template id and paste in root_interface_model_id in config.json,  but still met the same issue:

okay to set 0/false, but failed to set 1/true to Modbus

![image](https://user-images.githubusercontent.com/61225358/121056382-b94f6a00-c7f0-11eb-90f8-0c2a8a10be3b.png)

Information attached with more details in debug trace logs, kindly let us know it is correct. I checked debug logs butthere is still no error message. PnP Bridge always succeeded in receiving the commands in both scenarios, but the issue is that it cannot pass 1/true to Modbus/ModSim

I could reproduce the issue always, and you may also reproduce on your side to confirm. Kindly let me know if any questions in the reproducing steps. Thanks!

[info.zip](https://github.com/Azure/iot-plug-and-play-bridge/files/6610753/info.zip)

**Comment by dipannita08** [comment] 2021-06-08 16:40
@ChenhangLin 
Looks like the errors you were seeing before are no longer reproducing on your end. IoT hub logs look clean and so do PnP Bridge logs. What exactly are you seeing "not pass"? I have not been able to reproduce this issue since the beginning, and logs show no errors - so I'm curious if I can add more logging to catch whatever you're seeing. You also mentioned some videos capturing the issue - where are these located?

**Comment by dipannita08** [comment] 2021-07-12 19:14
Closing this out since there is no repro at hand, clean logs and we haven't heard back with any new information. Please feel free to reach out if you have a bug repro at hand and need help investigating.

**Closed by dipannita08** 2021-07-12 19:14 UTC
Labels: bug
